
BEGIN TRANSACTION;
DROP TABLE IF EXISTS geeignet;
DROP TABLE IF EXISTS gehoert_zu;
DROP TABLE IF EXISTS favorisiert;
DROP TABLE IF EXISTS bewertung;
DROP TABLE IF EXISTS benutzer;
DROP TABLE IF EXISTS produkt;
DROP TABLE IF EXISTS kategorie;
DROP TABLE IF EXISTS hauttyp;
COMMIT;