
BEGIN TRANSACTION;

DELETE from geeignet;
DELETE from gehoert_zu;
DELETE from favorisiert;
DELETE from bewertung;
DELETE from benutzer;
DELETE from produkt;
DELETE from kategorie;
DELETE from hauttyp;

DELETE from sqlite_sequence;

--Hauttyp
INSERT INTO hauttyp (bezeichnung) VALUES ("trocken"); --1
INSERT INTO hauttyp (bezeichnung) VALUES ("oelig"); --2
INSERT INTO hauttyp (bezeichnung) VALUES ("normal"); --3
INSERT INTO hauttyp (bezeichnung) VALUES ("mischhaut"); --4
INSERT INTO hauttyp (bezeichnung) VALUES ("sensibel"); --5

--Kategorie 
INSERT INTO kategorie (bezeichnung, beschreibung) VALUES ("Reinigung","Entfernt Schmutz/Talg, ohne die Hautbarriere zu stressen."); --1
INSERT INTO kategorie (bezeichnung, beschreibung) VALUES ("Feuchtigkeitscreme","Spendet Feuchtigkeit, stärkt Barriere, reduziert Trockenheit/Glanz."); --2
INSERT INTO kategorie (bezeichnung, beschreibung) VALUES ("Sonnencreme","UV-Schutz (UVA/UVB) für Alltag; wichtig gegen Irritation & Aging."); --3
INSERT INTO kategorie (bezeichnung, beschreibung) VALUES ("Serum/Booster","Wirkstoff-Targeting (z. B. Niacinamid, Hyaluron, Ceramide."); --4
INSERT INTO kategorie (bezeichnung, beschreibung) VALUES ("Peeling","Sanftes AHA/BHA/PHA für Textur, Poren, Schüppchen (nicht täglich)."); --5

--PRODUKTE
--trockene Haut -> Reinigung
s#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("CeraVe Hydrating Cleanser","Cremiger Reiniger für trockene & empfindliche Haut","feuchtigkeitsspendend, parfumfrei, barriere-stärkend, nicht komedogen",11.95,"Sanfter, cremiger Reiniger, der Schmutz und leichte Rückstände entfernt, ohne die Haut auszutrocknen. Ideal bei Spannungsgefühl und trockener, empfindlicher Haut. Nach der Reinigung fühlt sich die Haut weich und gepflegt an, ohne zu spannen.","Ceramide (stärken die Hautbarriere), Hyaluronsäure (bindet Wasser), Glycerin (Feuchthaltefaktor)","Morgens & abends auf feuchter Haut einmassieren und abspülen.","https://www.dm.de/cerave-cerave-feuchtigkeitsspendende-reinigungslotion-p3337875597180.html","CeraVe_Feuchtigkeitsspendende_Reinigungslotion.png"); --1
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("La Roche-Posay Toleriane Reinigungsmilch","Sehr milde Reinigungsmilch","sehr sanft, parfumfrei, alkoholfrei, beruhigend",15.95,"Sehr milde Reinigungsmilch für trockene und hochsensible Haut, die schnell reagiert. Reinigt ohne starkes Schäumen und ist dadurch oft weniger austrocknend als Gelreiniger. Ideal, wenn die Haut nach dem Waschen zu Rötungen oder Spannungsgefühl neigt.","Glycerin (spendet Feuchtigkeit), Thermalwasser (beruhigt und mindert Reizungen)","Abends auftragen und mit Wattepad abnehmen oder sanft abspülen.","https://www.dm.de/la-roche-posay-la-roche-posay-toleriane-reinigungsfluid-gesicht-und-augen-p3433422406599.html","La_Roche_Posay_Toleriane_Reinigungsfluid.png"); --2
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin UltraSensitive Reinigungslotion","Reinigung ohne Duftstoffe","reizarm, ultramild, parfumfrei, für hypersensible Haut",13.95,"Reinigungslotion für sehr empfindliche Haut, die möglichst wenig Reizpotenzial verträgt. Sie reinigt sanft und hilft dabei, Rötungen und Irritationen nicht zusätzlich zu triggern. Besonders geeignet, wenn du auf Duftstoffe oder „zu viel“ Pflege schnell reagierst.","Panthenol (beruhigt, unterstützt Regeneration)","1–2× täglich sanft verteilen und abnehmen oder abspülen.","https://www.shop-apotheke.com/beauty/8115115/eucerin-ultrasensitive-reinigungslotion-reduziert-roetungen-und-beruhigt-sehr-empfindliche-haut.htm","Eucerin_UltraSensitive_Reinigungslotion.png"); --3
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Med Reinigungsmilch","Milde Pflege für trockene Haut","parfumfrei, sanft, preiswert, feuchtigkeitserhaltend",2.95,"Alltags-Reinigungsmilch für trockene und empfindliche Haut zum sehr günstigen Preis. Reinigt mild und ist darauf ausgelegt, die Haut nicht „quietschig sauber“ zu entfetten. Gut für alle, die eine unkomplizierte Reinigung ohne Schnickschnack wollen.","Glycerin (zieht Wasser an), Panthenol (beruhigt und schützt)","Täglich morgens und/oder abends anwenden, danach abspülen oder abnehmen.","https://www.dm.de/balea-med-reinigungsmilch-ultra-sensitive-p4066447429220.html","Balea_Reinigungsmilch.png"); --4
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Avène Extremely Gentle Cleanser","Ultra-milde Reinigung","sehr verträglich, beruhigend, reizarm, für sehr trockene Haut",16.95,"Ultra-sanfter Cleanser für sehr empfindliche, trockene oder gereizte Haut. Die Formulierung ist bewusst minimalistisch gehalten und häufig auch dann angenehm, wenn andere Reiniger brennen. Ideal als „Sicherheitsprodukt“, wenn die Hautbarriere gerade gestresst ist.","Avène Thermalwasser (beruhigt, entzündungshemmend)","Morgens & abends sanft auftragen; optional abspülen oder mit Tuch abnehmen.","https://www.shop-apotheke.com/beauty/16537506/avene-tolerance-reinigungslotion.htm","Avene_Tolerance_Reinigungslotion.png"); --5
--trockene Haut -> Feuchtigkeit
s#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("CeraVe Feuchtigkeitscreme","Reichhaltige Pflege für trockene Haut","reichhaltig, parfumfrei, barriere-stärkend, langanhaltend",14.95,"Reichhaltige Creme für trockene bis sehr trockene Haut, die intensiv pflegt und die Hautbarriere unterstützt. Sie ist besonders praktisch, weil sie für Gesicht und Körper genutzt werden kann. Viele mögen sie, weil sie spürbar glättet und Trockenheitsstellen über den Tag hinweg reduziert.","Ceramide (reparieren Barriere), Hyaluronsäure (speichert Feuchtigkeit), Glycerin (reduziert Wasserverlust)","1–2× täglich auf die gereinigte Haut auftragen.","https://www.dm.de/cerave-feuchtigkeitscreme-p3337875597395.html","CeraVe_Feuchtigkeitscreme.png"); --6
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin UreaRepair PLUS 5%","Intensivpflege gegen Trockenheit","intensiv feuchtigkeitsspendend, glättend, barriere-stützend",18.95,"Intensivpflege, die speziell bei sehr trockener, rauer oder schuppiger Haut hilft. Urea kann Trockenheit spürbar reduzieren und die Haut wieder geschmeidiger machen. Besonders gut geeignet im Winter oder wenn die Haut zu „Krokodilhaut“-Gefühl neigt.","Urea 5% (natürlicher Feuchthaltefaktor, glättet), Ceramide (stärken Hautbarriere)","Abends oder nach Bedarf auftragen, besonders auf trockene Stellen.","https://www.dm.de/eucerin-urearepair-plus-5-p4005800218686.html","Eucerin_UreaRepair_PLUS.png"); --7
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("La Roche-Posay Lipikar Baume AP+M","Sehr reichhaltige Pflege","sehr reichhaltig, beruhigend, barriere-stärkend, rückfettend",19.95,"Sehr reichhaltiger Balm für trockene bis sehr trockene und empfindliche Haut. Er pflegt intensiv, reduziert Spannungsgefühl und unterstützt die Barriere langfristig. Besonders beliebt als „Winterrettung“ oder bei Haut, die schnell rau und gereizt wird.","Sheabutter (rückfettend, schützt), Niacinamid (stärkt Barriere, beruhigt)","1× täglich (oder nach Bedarf) auftragen.","https://www.dm.de/la-roche-posay-lipikar-baume-ap-m-p3337875751033.html","LaRochePosay_Lipikar_Baume_AP.png"); --8
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Weleda Skin Food Light","Natürliche Pflege für trockene Haut","natürliche Pflege, pflegend, leichter als Classic, duftend",8.95,"Leichtere Version der klassischen Skin Food – pflegend, aber nicht ganz so schwer auf der Haut. Gut, wenn du natürliche Öle und Kräuterextrakte magst und eine Creme suchst, die Trockenheit mildert. Durch den Duft ist sie eher etwas für Personen, die Duftstoffe gut vertragen.","Sonnenblumenöl (nährt und schützt), Kamille (beruhigend)","Täglich auftragen, besonders auf trockene Partien.","https://www.dm.de/weleda-skin-food-light-p4001638500525.html","Weleda_Skin_Food_Light.png"); --9
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Avène Hydrance RICH","Feuchtigkeitspflege für sehr trockene Haut","reichhaltig, beruhigend, feuchtigkeitsspendend, für sensible Haut",18.95,"Feuchtigkeitscreme, die speziell für trockene bis sehr trockene, empfindliche Haut gedacht ist. Sie versorgt die Haut spürbar mit Feuchtigkeit und macht sie weicher, ohne sofort wieder „zu verschwinden“. Ideal morgens, wenn du tagsüber weniger Spannungsgefühl haben möchtest.","Sheabutter (schützt vor Austrocknung), Thermalwasser (beruhigt, mindert Reizungen)","Morgens auf die gereinigte Haut auftragen.","https://www.dm.de/avene-hydrance-rich-p3282779317231.html","Avene_Hydrance_UVRiche.png"); --10
--trockene Haut -> Sonnnecreme
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("La Roche-Posay Anthelios Hydrating Cream SPF50+","Reichhaltiger Sonnenschutz für trockene & empfindliche Haut","SPF50+, feuchtigkeitsspendend, hoher UVA/UVB-Schutz, für sensible Haut",18.95,"Reichhaltige Sonnencreme für trockene und empfindliche Haut, die sich eher wie Pflege anfühlt. Sie bietet sehr hohen UVA- und UVB-Schutz und kann Spannungsgefühl durch Trockenheit reduzieren. Gut geeignet, wenn viele matte Fluids dir zu austrocknend sind.","Mexoryl SX/XL (moderne UV-Filter, hoher UVA/UVB-Schutz), Glycerin (bindet Feuchtigkeit), Thermalwasser (beruhigt)","Morgens als letzten Schritt großzügig auftragen und bei Bedarf nachlegen.","https://www.dm.de/la-roche-posay-anthelios-hydrating-cream-spf50-p3337875588875.html","LaRochePosay_Anthelios_Hydrating_Cream50+.png"); --11
s#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin Sensitive Protect SPF50+","Sonnenschutz speziell für trockene & sensible Haut","SPF50+, reizarm, antioxidativ, feuchtigkeitsspendend",17.95,"Sonnenschutz, der speziell auf empfindliche und trockene Haut ausgelegt ist. Schützt zuverlässig vor UVA/UVB-Strahlen und hilft durch antioxidative Inhaltsstoffe, UV-bedingten Stress abzufedern. Wenn du schnell Brennen bekommst, ist das oft eine angenehme Option.","Licochalcone A (antioxidativ, schützt vor UV-Stress), Glycerin (Feuchtigkeit), UV-Filter (UVA/UVB-Schutz)","Morgens großzügig auftragen, bei Sonne regelmäßig erneuern.","https://www.dm.de/eucerin-sensitive-protect-spf50-p4005800301622.html","Eucerin_Sensitive_Protect50+.png"); --12
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Nivea UV Gesicht Sensitive SPF50","Pflegender Sonnenschutz ohne Duftstoffe","SPF50, parfumfrei, pflegend, alltagstauglich",8.95,"Alltagstauglicher Sonnenschutz fürs Gesicht mit hoher Schutzleistung, der ohne Duftstoffe auskommt. Besonders interessant, wenn du eine günstige Option suchst, die nicht brennt und gleichzeitig etwas pflegt. Gut für empfindliche Haut, die schnell reagiert.","Vitamin E (Antioxidans), Glycerin (Feuchtigkeit), UV-Filter (UVA/UVB-Schutz)","Morgens großzügig auftragen, bei Bedarf erneuern.","https://www.dm.de/nivea-uv-gesicht-sensitive-spf50-p4005900463125.html","Nivea_UVGesicht_sensitive.png"); --13
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Bioderma Photoderm Creme SPF50+","Sehr hoher Sonnenschutz für trockene Haut","SPF50+, sehr schützend, feuchtigkeitsspendend, reichhaltig",19.95,"Sehr hoher Sonnenschutz mit cremiger, eher reichhaltiger Textur – passend für trockene Haut, die unter vielen Sonnenfluids spannt. Der Fokus liegt auf zuverlässigem Schutz und zusätzlicher Pflege. Wenn du es gerne cremig magst, ist das eine gute Option.","Cellular Bioprotection™ (zellschützendes Konzept), Glycerin (spendet Feuchtigkeit)","Morgens großzügig auftragen, bei Sonne regelmäßig nachlegen.","https://www.dm.de/bioderma-photoderm-creme-spf50-p3401579428378.html","Bioderma_Photoderm_Creme.png"); --14
--trockene Haut -> Serum/Booster
m#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("The Ordinary Hyaluronic Acid 2% + B5","Intensives Feuchtigkeitsserum für trockene Haut","feuchtigkeitsspendend, aufpolsternd, vegan, leicht",8.95,"Leichtes Feuchtigkeitsserum, das der Haut schnell „Wasser“ gibt und Trockenheitsfältchen optisch glatter wirken lassen kann. Sehr gut unter einer Creme, weil es die Haut aufnahmefähiger macht. Ideal, wenn du Feuchtigkeit willst, ohne ein schweres Gefühl.","Hyaluronsäure (bindet Wasser, polstert auf), Vitamin B5 (beruhigt, unterstützt Regeneration)","Morgens & abends vor der Creme auf leicht feuchter Haut auftragen.","https://www.douglas.de/de/p/3001047392","TheOrdinary_Hyaluronic_Acid.png"); --15
m#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Vichy Minéral 89","Stärkendes Feuchtigkeitsserum","barriere-stärkend, hydratisierend, schnell einziehend",21.95,"Ein sehr leichtes Serum, das die Hautbarriere unterstützen und gleichzeitig intensiv hydratisieren soll. Viele nutzen es als „Basis-Serum“ morgens oder abends, weil es schnell einzieht und sich gut kombinieren lässt. Besonders angenehm, wenn die Haut müde und trocken wirkt.","Hyaluron (intensive Hydration), Thermalwasser (stärkt, beruhigt)","Täglich morgens und/oder abends vor der Creme auftragen.","https://www.dm.de/vichy-mineral-89-p3337875597425.html","Vichy_Mineral89_Boost.png"); --16
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Hyaluron Booster","Günstiges Feuchtigkeitsserum","preiswert, feuchtigkeitsspendend, beruhigend",3.95,"Sehr günstiger Feuchtigkeitsbooster für den Alltag, der Trockenheitsgefühl reduzieren kann. Gut als Einstieg, wenn du Hyaluron testen willst, ohne viel Geld auszugeben. Lässt sich leicht unter Creme und Make-up tragen.","Hyaluronsäure (Feuchtigkeit), Panthenol (beruhigt und schützt)","Täglich vor der Creme auftragen.","https://www.dm.de/balea-hyaluron-booster-p4058172776792.html","Balea_Hyaluron_Booster.png"); --17
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin Hyaluron-Filler Moisture Booster","Intensiver Feuchtigkeitsbooster","sehr leicht, feuchtigkeitsspendend, aufpolsternd",18.95,"Leichter Moisture-Booster, der schnell einzieht und die Haut praller wirken lassen kann. Ideal, wenn du Feuchtigkeit möchtest, aber keine schwere Creme-Schicht. Besonders praktisch am Morgen oder unter Sonnencreme.","Hyaluron (polstert Trockenheitsfältchen), Glycerin (hält Feuchtigkeit in der Haut)","Morgens vor der Creme/Sonnencreme auftragen.","https://www.dm.de/eucerin-hyaluron-filler-moisture-booster-p4005800238370.html","Eucerin_Hyaluron_Filler_Boost_Serum.png"); --18
--trockene Haut -> Peeling
m#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("The Ordinary Lactic Acid 5% + HA","Sanftes AHA-Peeling für trockene Haut","mild exfolierend, glättend, feuchtigkeitsspendend",8.95,"Sehr sanftes AHA-Peeling für trockene Haut, das abgestorbene Hautschüppchen löst und die Haut glatter wirken lässt. Milchsäure ist im Vergleich zu stärkeren AHAs oft verträglicher und kann zusätzlich Feuchtigkeit unterstützen. Ideal, wenn du ein Peeling willst, aber Angst vor Reizung hast.","Milchsäure (löst Schüppchen, verbessert Glow), Hyaluron (schützt vor Austrocknung)","1–2× pro Woche abends auftragen, danach Creme verwenden.","https://www.douglas.de/de/p/3001047395","TheOrdinary_Lactic_Acid.png"); --19
s#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Paula's Choice Calm 1% BHA Lotion","Sehr mildes Peeling für trockene & empfindliche Haut","sehr mild, porenklärend, beruhigend",32.95,"Sehr mild formulierte BHA-Lotion, die Poren klären kann, ohne die Haut stark zu stressen. Durch die niedrige Dosierung ist sie häufig besser verträglich als klassische 2% BHA-Produkte. Gut, wenn du empfindliche Haut hast, aber trotzdem gegen verstopfte Poren arbeiten willst.","Salicylsäure 1% (klärt Poren sanft), Haferextrakt (beruhigt, mindert Rötungen)","Abends dünn auftragen, langsam einschleichen.","https://www.douglas.de/de/p/3001047420","Paulas_Choice_calm.png"); --20
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Beauty Expert PHA Toner","Sehr mildes chemisches Peeling","sehr sanft, feuchtigkeitsspendend, preiswert",4.95,"Sehr mildes Peeling-Toner-Konzept, das die Hautoberfläche glätten kann, ohne stark zu reizen. PHAs sind meist sanfter als viele AHAs und werden oft gut von trockener, empfindlicher Haut vertragen. Ideal, wenn du „ein bisschen Peeling“ für mehr Glow möchtest.","PHA (mildes Peeling, bindet zusätzlich Feuchtigkeit)","2× wöchentlich nach der Reinigung anwenden.","https://www.dm.de/balea-beauty-expert-pha-toner-p4058172776518.html","balea_pha_toner.jpg"); --21
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Avène Gentle Peeling Gel","Mechanisch-enzymatisches Peeling","sehr mild, beruhigend, für sensible Haut",17.95,"Sanftes Peeling-Gel mit sehr feinen Partikeln, das abgestorbene Hautschüppchen lösen kann, ohne stark zu rubbeln. Durch die milde Ausrichtung ist es eher für empfindliche Haut gedacht als klassische grobe Scrubs. Gut, wenn du ein weiches Hautgefühl möchtest, aber wenig Risiko eingehen willst.","Celluloseperlen (feine Peelingpartikel), Thermalwasser (beruhigt)","1× pro Woche auf feuchter Haut sanft massieren und abspülen.","https://www.dm.de/avene-gentle-peeling-p3282770111960.html","Avene_gentle_Peeling.png"); --22
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin DermoPure Soft Scrub","Mildes Peeling für trockene & unreine Haut","sanft, glättend, porenfreundlich",13.95,"Mildes Peeling, das sowohl gegen raue Haut als auch gegen Unreinheiten unterstützen kann, ohne zu aggressiv zu sein. Durch feine Partikel wird die Hautoberfläche geglättet, während Milchsäure zusätzlich sanft exfolieren kann. Gut, wenn du trocken bist, aber trotzdem zu verstopften Poren neigst.","Milchsäure (glättet, unterstützt sanfte Erneuerung), Feine Peelingpartikel (mechanische Entfernung von Schüppchen)","1× wöchentlich sanft einmassieren und abspülen.","https://www.dm.de/eucerin-dermopure-waschpeeling-p4005800238127.html","Eucerin_DermoPure_Waschpeeling.png"); --23



--mischhaut -> Reinigung
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("CeraVe Reinigungsgel","Sanfter Gelreiniger für normale bis Mischhaut","sanft reinigend, parfumfrei, barriere-stärkend, für Mischhaut geeignet",11.95,"Sanfter Gelreiniger für normale bis Mischhaut, der gründlich reinigt ohne die Haut auszutrocknen. Ideal, wenn die T-Zone schneller glänzt, die Wangen aber eher trocken sind. Die Haut fühlt sich nach dem Waschen sauber, aber nicht „quietschig“ oder spannig an.","Ceramide (stärken Hautbarriere, verhindern Feuchtigkeitsverlust), Niacinamid (reguliert Talg, beruhigt Rötungen), Glycerin (bindet Wasser in der Haut)","Morgens & abends auf feuchte Haut einmassieren und abspülen.","https://www.dm.de/cerave-reinigungsgel-p3337875597357.html | https://www.rossmann.de/de/pflege-und-duft-cerave-reinigungsgel/p/3337875597357","CeraVe_Reinigungsgel.png"); --23
s#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Med Ultra Sensitive Waschgel","Seifenfreier Reiniger ohne Duftstoffe","parfumfrei, sehr sanft, seifenfrei, für empfindliche Mischhaut",2.95,"Sehr mildes Waschgel für Mischhaut, die empfindlich reagiert oder schnell trocken wird. Reinigt ohne Duftstoffe und ist deshalb oft gut verträglich, selbst wenn die Haut schnell rötet. Ideal als unkomplizierte tägliche Reinigung für Gesicht und sensible Zonen.","Panthenol (beruhigt, fördert Regeneration), Glycerin (spendet Feuchtigkeit)","Morgens & abends auf feuchter Haut anwenden und abspülen.","https://www.dm.de/balea-med-ultra-sensitive-waschgel-p4058172920950.html","Balea_Med_Ultra_Sensitive_Waschgel.png"); --24
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Neutrogena Hydro Boost Reinigungsgel","Feuchtigkeitsspendende Reinigung","feuchtigkeitsspendend, leicht, erfrischend, für Mischhaut geeignet",6.95,"Feuchtigkeitsspendendes Reinigungsgel, das die Haut frisch und sauber macht, ohne nach dem Waschen zu spannen. Besonders angenehm, wenn du ein leichtes, geliges Hautgefühl magst und trotzdem Feuchtigkeit brauchst. Gut für Mischhaut, weil es reinigt, aber nicht unnötig austrocknet.","Hyaluronsäure (speichert Wasser, polstert Haut), Glycerin (verhindert Austrocknung)","Täglich morgens und/oder abends auf feuchte Haut einmassieren und abspülen.","https://www.dm.de/neutrogena-hydro-boost-reinigungsgel-p3574661389652.html | https://www.rossmann.de/de/pflege-und-duft-neutrogena-hydro-boost-reinigungsgel/p/3574661389652","Neutrogena_Hydro_Boost.png"); --25
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin DermatoCLEAN Reinigungsgel","Mildes Gel für empfindliche Mischhaut","mild, reizarm, feuchtigkeitsunterstützend, für sensible Mischhaut",12.95,"Mildes Reinigungsgel für empfindliche Mischhaut, das gründlich reinigt und die Haut gleichzeitig nicht aus dem Gleichgewicht bringt. Besonders gut geeignet, wenn du Reinigung willst, aber danach oft Trockenheit spürst. Hinterlässt ein sauberes, angenehmes Hautgefühl ohne starkes Entfetten.","APG-Komplex (besonders milde Tenside), Gluco-Glycerol (verbessert Feuchtigkeitsverteilung)","Morgens & abends auf feuchte Haut auftragen, einmassieren und abspülen.","https://www.dm.de/eucerin-dermatoclean-reinigungsgel-p4005800200131.html","Eucerin_DermatoCLEAN_Reinigungsgel.png"); --26
--mischhaut -> Feuchtigkeit
o#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("CeraVe Feuchtigkeitslotion","Leichte Pflege mit Barriereschutz","leicht, barriere-stärkend, parfumfrei, für Mischhaut geeignet",13.95,"Leichte Feuchtigkeitslotion, die die Hautbarriere stärkt und gleichzeitig nicht zu schwer wirkt – gut für Mischhaut. Sie hydratisiert zuverlässig und hilft, trockene Partien zu beruhigen, ohne die T-Zone unnötig zu fetten. Ideal, wenn du eine ausgewogene „One-and-done“-Pflege suchst.","Ceramide (reparieren Schutzbarriere), Hyaluronsäure (hydratisiert)","1–2× täglich auf die gereinigte Haut auftragen.","https://www.dm.de/cerave-feuchtigkeitslotion-p3337875597418.html","CeraVe_Feuchtigkeitslotion.png"); --27
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("La Roche-Posay Toleriane Fluid","Minimalistische Pflege für Mischhaut","minimalistisch, beruhigend, leicht, für sensible Haut",16.95,"Sehr leichtes Fluid für Mischhaut, das auf unnötige Reizstoffe verzichtet und die Haut beruhigt. Ideal, wenn du schnell auf Produkte reagierst oder Rötungen hast, aber trotzdem Feuchtigkeit brauchst. Hinterlässt ein angenehmes, gepflegtes Gefühl ohne schweren Film.","Glycerin (Feuchtigkeit), Thermalwasser (beruhigt sensible Haut)","Morgens auf die gereinigte Haut auftragen.","https://www.dm.de/la-roche-posay-toleriane-sensitive-fluid-p3337875735781.html","Toleriane_Sensitive_Fluid.png"); --28
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Aqua Feuchtigkeitscreme","Leichte Creme für Mischhaut","leicht, erfrischend, feuchtigkeitsspendend, preiswert",4.95,"Leichte Feuchtigkeitscreme für Mischhaut, die schnell einzieht und die Haut frisch wirken lässt. Ideal, wenn du eine unkomplizierte Creme suchst, die nicht schwer ist, aber trotzdem Hydration liefert. Besonders angenehm im Alltag oder im Sommer, wenn reichhaltige Cremes zu viel sind.","Hyaluronsäure (hydratisiert), Algenextrakt (antioxidativ, feuchtigkeitsspendend)","Täglich morgens und/oder abends anwenden.","https://www.dm.de/balea-aqua-feuchtigkeitscreme-p4058172921864.html","Balea_Gel_Aqua_Gesichtscreme.png"); --29
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Vichy Aqualia Thermal Light","Feuchtigkeitscreme für Mischhaut","leicht, mineralreich, beruhigend, langanhaltend feucht",19.95,"Leichte Feuchtigkeitscreme für Mischhaut, die die Haut den Tag über angenehm hydratisiert. Sie eignet sich gut, wenn du Feuchtigkeit möchtest, aber keine fettige Textur verträgst. Hinterlässt ein glattes, frisches Hautgefühl und ist ideal als Tagespflege.","Hyaluronsäure (langanhaltende Feuchtigkeit), Thermalwasser (mineralreich, beruhigend)","Morgens auf die gereinigte Haut auftragen.","https://www.dm.de/vichy-aqualia-thermal-leichte-creme-p3337875597432.html","Vichy_Aualia_Thermal_Feuchtigkeitspflege.png"); --30
--mischhaut -> Sonnencreme
o#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("La Roche-Posay Anthelios Invisible Fluid SPF50+","Sehr leichtes Sonnenschutzfluid für Misch- & empfindliche Haut","SPF50+, ultraleicht, kein Weißfilm, ideal unter Make-up",18.95,"Sehr leichtes Sonnenschutzfluid für Mischhaut und empfindliche Haut, das schnell einzieht und sich angenehm auf der Haut anfühlt. Es ist besonders beliebt, weil es wenig glänzt und meist keinen Weißfilm hinterlässt. Perfekt für den Alltag und als Make-up-Unterlage, wenn du Sonnenschutz nicht „spüren“ willst.","Mexoryl SX/XL (moderne UV-Filter, hoher UVA/UVB-Schutz), Glycerin (verhindert Austrocknung), Thermalwasser (beruhigt empfindliche Haut)","Morgens als letzten Pflegeschritt großzügig auftragen, bei Sonne erneuern.","https://www.dm.de/la-roche-posay-anthelios-invisible-fluid-spf50-p3337875730557.html | https://www.douglas.de/de/p/3001046915","LaRochePosay_InvisibleFluid_50+.png"); --31
o#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Eucerin Oil Control SPF50+","Mattierender Sonnenschutz für Mischhaut","SPF50+, mattierend, talgregulierend, sehr leicht",17.95,"Mattierender Sonnenschutz, der besonders gut für Mischhaut geeignet ist, weil er Glanz in der T-Zone reduzieren kann. Sehr angenehm, wenn du schnell fettig wirst, aber trotzdem hohen Schutz brauchst. Die Textur ist leicht und wird oft als sehr alltagstauglich beschrieben.","Carnitin (reguliert Talgproduktion), Licochalcone A (antioxidativ, entzündungshemmend), UV-Filter (UVA/UVB-Schutz)","Morgens großzügig auftragen, bei Sonne regelmäßig nachlegen.","https://www.dm.de/eucerin-oil-control-spf50-p4005800301646.html","Eucerin_Oil_Control_SunGel-Creme_50+.png"); --32
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Nivea UV Gesicht Mattierend SPF50","Mattierender Sonnenschutz für Mischhaut","SPF50, mattierendes Finish, alltagstauglich, gut verträglich",8.95,"Mattierender Sonnenschutz für Mischhaut, der im Alltag helfen kann, Glanz zu reduzieren und trotzdem hohen Schutz zu liefern. Gut, wenn du eine günstige Option suchst, die nicht stark brennt und sich angenehm tragen lässt. Je nach Haut kann er etwas reichhaltiger wirken, ist aber insgesamt sehr praktikabel.","Vitamin E (Antioxidans gegen UV-Stress), UV-Filter (Sonnenschutz)","Morgens großzügig auftragen, bei Sonne nachlegen.","https://www.dm.de/nivea-uv-gesicht-mattierend-spf50-p4005900463118.html | https://www.rossmann.de/de/pflege-und-duft-nivea-sun-uv-gesicht-mattierend-spf50/p/4005900463118","NIVEA_SUN_Gesichtsschutz.png"); --33
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Vichy Capital Soleil UV-Clear SPF50+","Sonnenschutz bei Mischhaut & Unreinheiten","SPF50+, für Unreinheiten, talgausgleichend, sehr leicht",19.95,"Sonnenschutz speziell für Mischhaut, die zu Unreinheiten und verstopften Poren neigt. Die Formulierung setzt auf ausgleichende Wirkstoffe, damit die Haut weniger glänzt und sich trotzdem geschützt anfühlt. Ideal, wenn du SPF willst, ohne Angst vor „Pickel durch Sonnencreme“.","Niacinamid (reguliert Talg, beruhigt), Salicylsäure (wirkt gegen verstopfte Poren), UV-Filter (Sonnenschutz)","Morgens auftragen, bei Sonne regelmäßig erneuern.","https://www.dm.de/vichy-capital-soleil-uv-clear-spf50-p3337875860629.html","Vichy_Capital_Soleil_50+.png"); --34
--mischhaut -> Serum/Booster
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Niacinamide Serum","Ausgleichendes Serum für Mischhaut","talgregulierend, porenverfeinernd, preiswert, leicht",4.95,"Ausgleichendes Serum für Mischhaut, das besonders in der T-Zone helfen kann, Glanz zu reduzieren und das Hautbild ebenmäßiger wirken zu lassen. Gut geeignet, wenn du sichtbare Poren hast oder zu kleinen Unreinheiten neigst. Die leichte Textur lässt sich sehr gut unter Creme oder SPF schichten.","Niacinamid 10% (verfeinert Poren, reguliert Talg), Zink (antibakteriell, talgregulierend)","Nach der Reinigung auftragen, danach Creme/SPF verwenden.","https://www.dm.de/balea-niacinamide-serum-p4058172776518.html","Vichy_Capital_Soleil_50+.png"); --35
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("La Roche-Posay Niacinamide 10 Serum","Ausgleichendes Serum bei Unreinheiten","porenverfeinernd, talgausgleichend, beruhigend",34.95,"Ausgleichendes Serum für Mischhaut, besonders wenn du zu Unreinheiten, Rötungen oder unruhiger Textur neigst. Niacinamid kann helfen, das Hautbild zu glätten und die Talgproduktion zu regulieren. Ideal als Abendserum, wenn du gezielt an Poren und Hautbalance arbeiten willst.","Niacinamid (Poren & Rötungen, Talgregulation), Hyaluronsäure (Feuchtigkeit)","Abends nach der Reinigung auftragen.","https://www.dm.de/la-roche-posay-niacinamide-10-serum-p3337875861091.html","LaRochePosay_Niacinamide10Serum.png"); --36
o#INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Geek & Gorgeous B-Bomb","Leichtes Niacinamid-Serum","talgkontrollierend, leicht, porenfreundlich, für Mischhaut",10.95,"Leichtes Niacinamid-Serum, das speziell für ein ausgeglicheneres Hautbild bei Mischhaut entwickelt ist. Gut geeignet, wenn du Glanz reduzieren möchtest, aber keine schweren Texturen verträgst. Lässt sich einfach in fast jede Routine integrieren und ist angenehm unter Creme oder SPF.","Niacinamid 10% (Hautbildverbesserung, Talgregulation), Zink PCA (Talgkontrolle, antibakteriell)","Täglich nach der Reinigung anwenden.","https://geekandgorgeous.com/products/b-bomb","GeekandGorgeous_BBomb_Serum.png"); --37
--mischhaut -> Peeling
INSERT INTO produkt (name,bezeichnung,merkmal,preis,beschreibung,inhaltsstoffe,anwendung,shop_link,bild) VALUES ("Balea Beauty Expert Peeling Toner","Mildes chemisches Peeling","einsteigerfreundlich, glättend, mild, preiswert",4.95,"Mildes Peeling-Toner-Produkt für Mischhaut, das die Hautoberfläche glätten und den Teint frischer wirken lassen kann. Durch die Kombination aus AHA und PHA ist es oft sanfter als sehr starke Peelings. Ideal als Einstieg, wenn du Peeling testen möchtest, ohne direkt ein „hartes“ Produkt zu nehmen.","AHA (glättet Hautoberfläche), PHA (sehr mild, feuchtigkeitsspendend)","Abends anwenden, langsam starten und nicht täglich übertreiben.","https://www.dm.de/balea-beauty-expert-aha-pha-peeling-toner-p4058172776556.html","Balea_Liquid_Peeling.png"); --38



--Benutzer
INSERT INTO benutzer (passwort_hash,name,email,hauttyp_id) VALUES ("HASH1","Tiberja Gündüz","tiberja.gdz@gmail.com","1"); --1
INSERT INTO benutzer (passwort_hash,name,email,hauttyp_id) VALUES ("HASH2","Lina Kaufmann","lina.kfm@gmail.com","2"); --2

--Bewertung
INSERT INTO bewertung (produkt_id,benutzer_id,sterne,kommentar) VALUES ("2","2","4","sehr gutes Produkt"); --CeraVe Feuchtigkeitscreme
INSERT INTO bewertung (produkt_id,benutzer_id,sterne,kommentar) VALUES ("2","2","4","sehr gutes Produkt");


--Favoriten
INSERT INTO favorisiert (produkt_id,benutzer_id) VALUES ("2","2"); 

--gehört zu
--Reinigung

--Feuchtigkeitscremes
INSERT INTO gehoert_zu (produkt_id,kategorie_id) VALUES ("2","2"); --CeraVe Feuchtigkeitscreme

--Sonnencreme

--Serum/Booster

--Peeling


--geeignet
--trocken
INSERT INTO geeignet (produkt_id,hauttyp_id) VALUES ("1","1"); --CeraVe Feuchtigkeitscreme

--ölig

--normal

--mischhaut

--sensibel

COMMIT;



